Rotate Kernel
IntelLabs/hec-p-isa-tools pull request #44
Opened 2024-09-13 19:56 UTC by christopherngutierrez

## Proposed changes

Added rotate kernel, which has been tested and validated to work.

Minor changes (to avoid code replication):
- Created a helper function for common Polys in Relin/Rotate kernels
- Added a fix index to the KeyMul, which is different for Relin/Rotate kernels

## Types of changes

What types of changes does your code introduce to the HE Toolkit project?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating
the PR. If you are unsure about any of them, do not hesitate to ask. We are
here to help! This is simply a reminder of what we are going to look for before
merging your code._

- [ ] I have read the [CONTRIBUTING](https://github.com/IntelLabs/hec-p-isa-tools/blob/main/CONTRIBUTING.md) agreement
- [ ] Current formatting and unit tests / base functionality passes locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

2024-09-16 23:06 UTC, kylanerace approved these changes
LGTM, tested and running E2E

2024-09-17 19:10 UTC, faberga commented on kerngen/kerngen.py
Hi @christopherngutierrez,   why an empty file?

2024-09-17 19:12 UTC, faberga commented
This PR is dependent on PR #43 and should not be merged before it.

2024-09-18 19:57 UTC, faberga requested changes

2024-09-18 19:57 UTC, faberga commented on kerngen/pisa_generators/relin.py
> +        opts = mixed_to_pisa_ops(
This was resolved in the Relin PR but resurface in the Rotate. Sounds as the rotate code has not been rebased correctly.

2024-09-18 19:57 UTC, faberga commented on kerngen/pisa_generators/relin.py
> +        return opts
Same as above.

2024-09-27 19:41 UTC, faberga commented
Closed as this PR has been superseded by PR #48

2024-09-27 19:41 UTC, closed without merging