BGV Rotate Kernel
IntelLabs/hec-p-isa-tools pull request #48
Opened 2024-09-20 20:58 UTC by christopherngutierrez

## Proposed changes

Adds Rotate Kernel for BGV. Tested for 16k Poly mod. 
rotate.py - implementation of rotate kernel
manifest.json - adds rotate entry to BGV manifest

## Types of changes

What types of changes does your code introduce to the HE Toolkit project?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating
the PR. If you are unsure about any of them, do not hesitate to ask. We are
here to help! This is simply a reminder of what we are going to look for before
merging your code._

- [x] I have read the [CONTRIBUTING](https://github.com/IntelLabs/hec-p-isa-tools/blob/main/CONTRIBUTING.md) agreement
- [x] Current formatting and unit tests / base functionality passes locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [x] I have added necessary documentation (if appropriate)
- [x] Any dependent changes have been merged and published in downstream modules

## Further comments

2024-09-24 18:03 UTC, faberga commented on kerngen/pisa_generators/rotate.py
> +from .relin import KeyMul, DigitDecompExtend, extract_last_part_polys
```suggestion
from .basic import Add, KeyMul, mixed_to_pisa_ops, extract_last_part_polys
from .decomp import DigitDecompExtend
```

2024-09-24 18:05 UTC, faberga commented on kerngen/pisa_generators/rotate.py
> +from .relin import KeyMul, DigitDecompExtend, extract_last_part_polys
Hi @christopherngutierrez, remember that KeyMul, extract_last_part_polys, and DigitDecompExtend were moved out from relin.py by the refactoring introduced by PR #47

2024-09-24 18:07 UTC, faberga requested changes
See suggested code changes in rotate.py

2024-09-25 16:56 UTC, faberga approved these changes

2024-09-26 20:46 UTC, faberga requested changes
Hi @christopherngutierrez 
Now that we have the bug fix for the NTT, let's re-run the tests for 16K, 32K, 64K and 128K polynomials.

2024-09-26 21:23 UTC, christopherngutierrez commented
> Hi @christopherngutierrez Now that we have the bug fix for the NTT, let's re-run the tests for 16K, 32K, 64K and 128K polynomials.

@faberga confirmed working for NTT/INTT, Relin, and Rotate kernels for 16k, 32k, 64K, and 128K.

2024-09-27 19:38 UTC, faberga approved these changes

2024-09-27 19:39 UTC, faberga approved these changes

2024-09-27 20:21 UTC, jobottle approved these changes
Looks good

2024-09-27 20:24 UTC, merged